### ISSUE TITLE
Conversion Mode Copy is invalid

### ISSUE THREAD

**Issue by awiegerig** [mipimipi/smsync#1]
When trying to execute smsync with the configuration file from the README I receive the following error.

smsync (Smart Music Sync) 2.0.2.r6.g25240f7
Copyright (C) 2018 Michael Picht <https://github.com/mipimipi/smsync>
Error: Rule #1: 'copy' is not a valid conversion
Usage:
  smsync [options]

Flags:
  -a, --add-only   only add files
  -h, --help       help for smsync
  -l, --log        switch on logging
      --version    version for smsync

**Comment by mipimipi** [comment]
Thanks for reporting. I will look into it. But that may take a while :-(

**Comment by mipimipi** [comment]
The documentation is a bit strange. Copying your config file contents as shown at Github, exactly, I get: "Error: Rule #1: 'copy' is not a valid conversion". There is then no help anywhere I could see that would tell you what valid conversion options actually were.

I removed the Rule 1 and Rule 2 shown in the Github doco and the conversion process started well. But it wasn't an encouraging start when the only available doco appears wrong!

[https://bbs.archlinux.org/viewtopic.php?pid=1813433#p1813433](url)

**Comment by mipimipi** [comment]
@awiegerig You are not the only user experiencing this error. Until I am able to fix that, a workaround might help you, see [https://bbs.archlinux.org/viewtopic.php?pid=1813433#p1813433](url)

**Comment by mipimipi** [comment]
Solved with 3.0.1
